edition                     = "2021"
fn_params_layout            = "Tall"
fn_single_line              = true
format_code_in_doc_comments = true
format_generated_files      = true
format_macro_bodies         = false
format_macro_matchers       = true
imports_granularity         = "Module"
imports_layout              = "HorizontalVertical"
group_imports               = "StdExternalCrate"
max_width                   = 100
reorder_impl_items          = true
tab_spaces                  = 2
use_field_init_shorthand    = true
use_small_heuristics        = "Default"
